"apiVersion": v1
"kind": ConfigMap
"metadata":
  "name": prometheus-config
  "namespace": simpelv2
"data":
  "prometheus.yml": "\nglobal:\n  scrape_interval: 15s\nscrape_configs:\n  - job_name: 'simpelv2'\n    static_configs:\n \
    \     - targets: ['localhost:9090']\n"
