-- ============================================================================
-- MIGRATION 046: No-op (realm soft-delete migration moved to 048)
-- ============================================================================
-- This file was originally created for the realm soft-delete unique index
-- migration but was renumbered to 048_realm_soft_delete_unique_index.sql.
--
-- This file is intentionally left as a no-op to avoid breaking the migration
-- runner on databases that may have already recorded version 046.
-- ============================================================================
