-- ============================================================================
-- THIS FILE IS INTENTIONALLY EMPTY
-- ============================================================================
-- This migration was renumbered to 048_realm_soft_delete_unique_index.sql
-- because version 046 conflicts with the pre-existing
-- 046_user_extended_fields.sql. Both files resolve to version 46 in the
-- migration runner, causing this one to be silently skipped on databases
-- that already applied 046_user_extended_fields.
--
-- See: 048_realm_soft_delete_unique_index.sql
-- ============================================================================
