[build]
target = "index.html"
dist = "dist"
release = true

[[build.wasm_opt]]
args = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int", "--enable-sign-ext", "--enable-mutable-globals", "--enable-reference-types"]
