[package]
name = "hash-password"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
argon2 = { version = "0.5", features = ["std"] }
password-hash = { version = "0.5", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["std"] }
hmac = "0.12"
sha2 = "0.10"
hkdf = "0.12"
hex = "0.4"
