[build]
target = "index.html"
dist = "dist"

[[build.wasm-bindgen]]
target = "web"

[build.rust]
optimization-level = "s"
lto = true

[serve]
port = 8085
open = false

[watch]
watch = ["src", "styles"]
ignore = ["target", "dist"]
