[build]
target = "index.html"
dist = "dist"
release = true

[[build.wasm_opt]]
args = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int", "--enable-sign-extension", "--enable-reference-types"]

[serve]
port = 8094
addresses = ["0.0.0.0"]
open = false

[watch]
watch = ["src", "styles"]
ignore = ["target", "dist", "Cargo.lock", ".git"]
