[package]
name = "pidsus-microfrontend"
version.workspace = true
edition.workspace = true

[dependencies]
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
lib-ui = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlInputElement", "Window", "History"] }
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"
gloo-net = { workspace = true, features = ["http"] }

[lib]
crate-type = ["cdylib"]
name = "pidsus_microfrontend"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
