version: "3.9"

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #  - "5432:5432"
    networks:
      - simpel-net

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    command: buffalo dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - simpel-net

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
      - VITE_PORT=5173
      - VITE_HOST=0.0.0.0
    networks:
      - simpel-net

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - simpel-net

volumes:
  pgdata:

networks:
  simpel-net:
