# layanan-integrasi/config/config.yaml

server:
  port: 8080
  mode: "release"

database:
  host: ""
  port: 0
  user: ""
  password: ""
  name: ""

mysimkari:
  url: "https://mysimkari.kejaksaan.go.id/api/anbut"
  token: ""
