#!/bin/sh
# fetch-secrets.sh — Init container script untuk simpelv1 Laravel.
#
# Auth ke Secreton via Kubernetes ServiceAccount JWT (Kubernetes Auth Backend),
# fetch secret dari kv/simpelv1/* dan kv/postgres/simpelv2, render ke /app/runtime/.env.
#
# Env wajib (di-inject oleh _workload.tpl saat secretonAuth.enabled=true):
#   SECRETON_ADDR              — URL Secreton (http://secreton:8200)
#   SECRETON_AUTH_METHOD       — selalu "kubernetes" untuk pod-based auth
#   SECRETON_AUTH_ROLE         — nama role di Kubernetes Auth Backend (= simpelv1)
#   SECRETON_K8S_TOKEN_PATH    — path projected SA token (/var/run/secrets/tokens/secreton-token)
#
# Output: /app/runtime/.env yang akan di-shared via emptyDir ke main container Laravel.

set -eu

: "${SECRETON_ADDR:?SECRETON_ADDR wajib}"
: "${SECRETON_AUTH_ROLE:?SECRETON_AUTH_ROLE wajib}"
: "${SECRETON_K8S_TOKEN_PATH:=/var/run/secrets/tokens/secreton-token}"
OUTPUT_DIR="${OUTPUT_DIR:-/app/runtime}"
OUTPUT_FILE="$OUTPUT_DIR/.env"

mkdir -p "$OUTPUT_DIR"

# Step 1: Login ke Secreton dengan SA JWT.
echo ">>> [1/3] Login ke Secreton sebagai role=$SECRETON_AUTH_ROLE..."
SA_JWT=$(cat "$SECRETON_K8S_TOKEN_PATH")
LOGIN_RESP=$(curl -fsS -X POST \
  -H "Content-Type: application/json" \
  -d "{\"role\":\"$SECRETON_AUTH_ROLE\",\"jwt\":\"$SA_JWT\"}" \
  "$SECRETON_ADDR/v1/auth/kubernetes/login")
TOKEN=$(echo "$LOGIN_RESP" | sed -n 's/.*"client_token":"\([^"]*\)".*/\1/p')
[ -n "$TOKEN" ] || { echo "ERROR: login gagal. Response: $LOGIN_RESP"; exit 1; }
echo "    OK (token TTL=$(echo "$LOGIN_RESP" | sed -n 's/.*"lease_duration":\([0-9]*\).*/\1/p') sec)"

# Step 2: Fetch secrets dari paths yang diizinkan policy simpelv1.
echo ">>> [2/3] Fetch secrets..."
fetch_kv() {
  local path=$1
  curl -fsS -H "X-Secreton-Token: $TOKEN" "$SECRETON_ADDR/v1/kv/data/$path"
}

# kv/simpelv1/* berisi APP_KEY, dan field lain Laravel-specific.
SIMPELV1_DATA=$(fetch_kv "simpelv1/app" || echo '{"data":{"data":{}}}')
# kv/postgres/simpelv2 berisi DB_USERNAME, DB_PASSWORD, DB_HOST, DB_DATABASE.
POSTGRES_DATA=$(fetch_kv "postgres/simpelv2" || echo '{"data":{"data":{}}}')

extract() {
  echo "$1" | sed -n "s/.*\"$2\":\"\([^\"]*\)\".*/\1/p"
}

APP_KEY=$(extract "$SIMPELV1_DATA" "app_key")
DB_USERNAME=$(extract "$POSTGRES_DATA" "username")
DB_PASSWORD=$(extract "$POSTGRES_DATA" "password")

# Step 3: Render .env (overwrite atomic via temp file).
echo ">>> [3/3] Render $OUTPUT_FILE..."
TMP=$(mktemp "${OUTPUT_FILE}.XXXXXX")
{
  echo "# Auto-generated by fetch-secrets.sh — DO NOT EDIT (will be overwritten on pod start)"
  echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "APP_KEY=base64:${APP_KEY}"
  echo "DB_USERNAME=${DB_USERNAME}"
  echo "DB_PASSWORD=${DB_PASSWORD}"
  # Pass-through env yang sudah di-set oleh ConfigMap simpelv1-env (DB_HOST, DB_DATABASE, dll).
  # Laravel akan baca .env + env vars (env() helper merge keduanya).
} > "$TMP"
chmod 0640 "$TMP"
mv "$TMP" "$OUTPUT_FILE"

echo "✓ Done. Wrote: $OUTPUT_FILE"
ls -la "$OUTPUT_FILE"
