[build]
target = "index.html"
dist = "dist"
wasm_opt = false

[[build.wasm_opt]]
args = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int", "--enable-sign-ext", "--enable-mutable-globals", "--enable-reference-types"]

[[build.wasm-bindgen]]
target = "web"

[build.rust]
optimization-level = "s"
lto = true

[serve]
port = 8085
open = false

[watch]
watch = ["src", "styles"]
ignore = ["target", "dist"]
