// ============================================================================
// Penghapusan BMN Models
// Description: Data models for SK Penghapusan BMN workflow
// Requirements: REQ-W001
//
// Flow:
//   Draft(4000) → SubmitWilayah(4001) → SubmitPusat(4003) → VerifikasiPusat(4004) →
//   KonsepSKGenerated(4005) → SKSigned(4006) → Completed(4007)
//   Validator Wilayah can return: ReturnedToOperator(4002)
//   Validator Pusat can reject: Rejected(4008)
// ============================================================================

use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;
use validator::Validate;

/// Workflow status codes for SK Penghapusan BMN
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
pub enum PenghapusanBmnStatus {
    /// Draft by operator satker
    Draft = 4000,
    /// Submitted to Validator Wilayah
    SubmitWilayah = 4001,
    /// Returned to Operator by Validator Wilayah
    ReturnedToOperator = 4002,
    /// Forwarded to Validator Pusat by Validator Wilayah
    SubmitPusat = 4003,
    /// Validator Pusat verifying
    VerifikasiPusat = 4004,
    /// Konsep SK generated by Validator Pusat
    KonsepSKGenerated = 4005,
    /// SK signed and PDF uploaded
    SKSigned = 4006,
    /// Process completed
    Completed = 4007,
    /// Rejected by Validator Pusat
    Rejected = 4008,
}

impl PenghapusanBmnStatus {
    pub fn from_code(code: i32) -> Option<Self> {
        match code {
            4000 => Some(Self::Draft),
            4001 => Some(Self::SubmitWilayah),
            4002 => Some(Self::ReturnedToOperator),
            4003 => Some(Self::SubmitPusat),
            4004 => Some(Self::VerifikasiPusat),
            4005 => Some(Self::KonsepSKGenerated),
            4006 => Some(Self::SKSigned),
            4007 => Some(Self::Completed),
            4008 => Some(Self::Rejected),
            _ => None,
        }
    }

    pub fn to_code(self) -> i32 {
        self as i32
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::Draft => "Draft",
            Self::SubmitWilayah => "Diajukan ke Validator Wilayah",
            Self::ReturnedToOperator => "Dikembalikan ke Operator",
            Self::SubmitPusat => "Diajukan ke Validator Pusat",
            Self::VerifikasiPusat => "Verifikasi Pusat",
            Self::KonsepSKGenerated => "Konsep SK Digenerate",
            Self::SKSigned => "SK Ditandatangani",
            Self::Completed => "Selesai",
            Self::Rejected => "Ditolak",
        }
    }

    pub fn to_state_name(&self) -> &'static str {
        match self {
            Self::Draft => "DRAFT",
            Self::SubmitWilayah => "SUBMIT_WILAYAH",
            Self::ReturnedToOperator => "RETURNED_TO_OPERATOR",
            Self::SubmitPusat => "SUBMIT_PUSAT",
            Self::VerifikasiPusat => "VERIFIKASI_PUSAT",
            Self::KonsepSKGenerated => "KONSEP_SK_GENERATED",
            Self::SKSigned => "SK_SIGNED",
            Self::Completed => "COMPLETED",
            Self::Rejected => "REJECTED",
        }
    }

    pub fn from_state_name(name: &str) -> Option<Self> {
        match name {
            "DRAFT" => Some(Self::Draft),
            "SUBMIT_WILAYAH" | "SUBMITTED" => Some(Self::SubmitWilayah),
            "RETURNED_TO_OPERATOR" => Some(Self::ReturnedToOperator),
            "SUBMIT_PUSAT" | "REVIEWED" => Some(Self::SubmitPusat),
            "VERIFIKASI_PUSAT" => Some(Self::VerifikasiPusat),
            "KONSEP_SK_GENERATED" => Some(Self::KonsepSKGenerated),
            "SK_SIGNED" | "APPROVED" => Some(Self::SKSigned),
            "COMPLETED" => Some(Self::Completed),
            "REJECTED" => Some(Self::Rejected),
            _ => None,
        }
    }

    /// Check if transition to target status is allowed
    pub fn can_transition_to(&self, target: Self) -> bool {
        use PenghapusanBmnStatus::*;
        match self {
            Draft => matches!(target, SubmitWilayah),
            SubmitWilayah => matches!(target, SubmitPusat | ReturnedToOperator),
            ReturnedToOperator => matches!(target, SubmitWilayah),
            SubmitPusat => matches!(target, VerifikasiPusat),
            VerifikasiPusat => matches!(target, KonsepSKGenerated | Rejected),
            KonsepSKGenerated => matches!(target, SKSigned),
            SKSigned => matches!(target, Completed),
            Completed | Rejected => false,
        }
    }

    pub fn allowed_transitions(&self) -> Vec<Self> {
        use PenghapusanBmnStatus::*;
        match self {
            Draft => vec![SubmitWilayah],
            SubmitWilayah => vec![SubmitPusat, ReturnedToOperator],
            ReturnedToOperator => vec![SubmitWilayah],
            SubmitPusat => vec![VerifikasiPusat],
            VerifikasiPusat => vec![KonsepSKGenerated, Rejected],
            KonsepSKGenerated => vec![SKSigned],
            SKSigned => vec![Completed],
            Completed | Rejected => vec![],
        }
    }
}

impl Default for PenghapusanBmnStatus {
    fn default() -> Self {
        Self::Draft
    }
}

/// Penghapusan BMN entity
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenghapusanBmn {
    pub id: Uuid,
    pub satker_id: Uuid,
    pub asset_id: Uuid,
    pub kode_barang: String,
    pub nama_barang: String,
    pub nup: String,
    pub tanggal_penghapusan: NaiveDate,
    pub alasan: String,
    pub metode_penghapusan: String,
    pub nilai_residu: Option<f64>,
    pub status: String,
    pub status_kode: i32,

    // Lampiran
    pub lampiran_persyaratan: Option<String>,
    pub lampiran_pendukung: Value,
    pub catatan_operator: Option<String>,

    // Validator Wilayah
    pub catatan_validator_wilayah: Option<String>,
    pub validator_wilayah_id: Option<Uuid>,
    pub tanggal_submit_wilayah: Option<DateTime<Utc>>,
    pub tanggal_verifikasi_wilayah: Option<DateTime<Utc>>,

    // Validator Pusat
    pub catatan_validator_pusat: Option<String>,
    pub validator_pusat_id: Option<Uuid>,
    pub tanggal_submit_pusat: Option<DateTime<Utc>>,
    pub tanggal_verifikasi_pusat: Option<DateTime<Utc>>,

    // SK Document
    pub konsep_sk_url: Option<String>,
    pub konsep_sk_generated_at: Option<DateTime<Utc>>,
    pub signed_sk_pdf_url: Option<String>,
    pub signed_sk_pdf_uploaded_at: Option<DateTime<Utc>>,
    pub is_completed: bool,

    // Legacy fields
    pub document_id: Option<Uuid>,
    pub document_url: Option<String>,

    pub created_by: Uuid,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Create penghapusan BMN request
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreatePenghapusanBmnRequest {
    pub satker_id: Uuid,
    pub asset_id: Uuid,
    pub kode_barang: String,
    #[validate(length(min = 1, max = 255))]
    pub nama_barang: String,
    #[validate(length(min = 1, max = 50))]
    pub nup: String,
    pub tanggal_penghapusan: NaiveDate,
    #[validate(length(min = 10, max = 1000))]
    pub alasan: String,
    #[validate(length(min = 1, max = 100))]
    pub metode_penghapusan: String,
    pub nilai_residu: Option<f64>,
    // Lampiran persyaratan (required)
    #[validate(length(min = 1, message = "Lampiran persyaratan wajib dilampirkan"))]
    pub lampiran_persyaratan: String,
    pub catatan_operator: Option<String>,
}

/// Update penghapusan BMN request
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct UpdatePenghapusanBmnRequest {
    pub tanggal_penghapusan: Option<NaiveDate>,
    #[validate(length(min = 10, max = 1000))]
    pub alasan: Option<String>,
    #[validate(length(min = 1, max = 100))]
    pub metode_penghapusan: Option<String>,
    pub nilai_residu: Option<f64>,
    pub lampiran_persyaratan: Option<String>,
    pub catatan_operator: Option<String>,
}

/// Penghapusan BMN list filters
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenghapusanBmnFilters {
    pub satker_id: Option<Uuid>,
    pub status: Option<String>,
    pub status_kode: Option<i32>,
    pub metode_penghapusan: Option<String>,
    pub tahun: Option<i32>,
}

/// Request for validator wilayah action
#[derive(Debug, Clone, Deserialize)]
pub struct ValidatorWilayahActionRequest {
    /// "forward" to forward to pusat, "return" to return to operator
    pub aksi: String,
    pub catatan: Option<String>,
}

/// Request for validator pusat action
#[derive(Debug, Clone, Deserialize)]
pub struct ValidatorPusatActionRequest {
    /// "verify" to proceed, "reject" to reject
    pub aksi: String,
    pub catatan: Option<String>,
}

/// Request to upload signed SK PDF
#[derive(Debug, Clone, Deserialize)]
pub struct UploadSignedSKRequest {
    pub signed_sk_pdf_url: String,
}

/// Request for workflow transition
#[derive(Debug, Clone, Deserialize)]
pub struct WorkflowTransitionRequest {
    pub target_status: i32,
    pub catatan: Option<String>,
}

/// Penghapusan BMN detail response
#[derive(Debug, Clone, Serialize)]
pub struct PenghapusanBmnDetailResponse {
    #[serde(flatten)]
    pub penghapusan: PenghapusanBmn,
    pub allowed_transitions: Vec<PenghapusanTransitionInfo>,
    pub can_generate_sk: bool,
    pub can_upload_signed_sk: bool,
}

/// Transition info
#[derive(Debug, Clone, Serialize)]
pub struct PenghapusanTransitionInfo {
    pub status_kode: i32,
    pub status_nama: String,
    pub requires_comment: bool,
}

impl PenghapusanBmn {
    /// Create from database row
    pub fn from_row(row: &tokio_postgres::Row) -> Self {
        let status_str: String = row.get("status");
        let status_kode = PenghapusanBmnStatus::from_state_name(&status_str)
            .map(|s| s.to_code())
            .unwrap_or(4000);
        Self {
            id: row.get("id"),
            satker_id: row.get("satker_id"),
            asset_id: row.get("asset_id"),
            kode_barang: row.get("kode_barang"),
            nama_barang: row.get("nama_barang"),
            nup: row.get("nup"),
            tanggal_penghapusan: row.get("tanggal_penghapusan"),
            alasan: row.get("alasan"),
            metode_penghapusan: row.get("metode_penghapusan"),
            nilai_residu: row.get("nilai_residu"),
            status: status_str,
            status_kode,
            lampiran_persyaratan: row.try_get("lampiran_persyaratan").ok().flatten(),
            lampiran_pendukung: row.try_get("lampiran_pendukung").unwrap_or(serde_json::json!([])),
            catatan_operator: row.try_get("catatan_operator").ok().flatten(),
            catatan_validator_wilayah: row.try_get("catatan_validator_wilayah").ok().flatten(),
            validator_wilayah_id: row.try_get("validator_wilayah_id").ok().flatten(),
            tanggal_submit_wilayah: row.try_get("tanggal_submit_wilayah").ok().flatten(),
            tanggal_verifikasi_wilayah: row.try_get("tanggal_verifikasi_wilayah").ok().flatten(),
            catatan_validator_pusat: row.try_get("catatan_validator_pusat").ok().flatten(),
            validator_pusat_id: row.try_get("validator_pusat_id").ok().flatten(),
            tanggal_submit_pusat: row.try_get("tanggal_submit_pusat").ok().flatten(),
            tanggal_verifikasi_pusat: row.try_get("tanggal_verifikasi_pusat").ok().flatten(),
            konsep_sk_url: row.try_get("konsep_sk_url").ok().flatten(),
            konsep_sk_generated_at: row.try_get("konsep_sk_generated_at").ok().flatten(),
            signed_sk_pdf_url: row.try_get("signed_sk_pdf_url").ok().flatten(),
            signed_sk_pdf_uploaded_at: row.try_get("signed_sk_pdf_uploaded_at").ok().flatten(),
            is_completed: row.try_get("is_completed").unwrap_or(false),
            document_id: row.get("document_id"),
            document_url: row.get("document_url"),
            created_by: row.get("created_by"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_penghapusan_status_flow() {
        let draft = PenghapusanBmnStatus::Draft;
        assert!(draft.can_transition_to(PenghapusanBmnStatus::SubmitWilayah));
        assert!(!draft.can_transition_to(PenghapusanBmnStatus::SubmitPusat));

        let wil = PenghapusanBmnStatus::SubmitWilayah;
        assert!(wil.can_transition_to(PenghapusanBmnStatus::SubmitPusat));
        assert!(wil.can_transition_to(PenghapusanBmnStatus::ReturnedToOperator));

        let verif = PenghapusanBmnStatus::VerifikasiPusat;
        assert!(verif.can_transition_to(PenghapusanBmnStatus::KonsepSKGenerated));
        assert!(verif.can_transition_to(PenghapusanBmnStatus::Rejected));
        assert!(!verif.can_transition_to(PenghapusanBmnStatus::ReturnedToOperator));

        let signed = PenghapusanBmnStatus::SKSigned;
        assert!(signed.can_transition_to(PenghapusanBmnStatus::Completed));

        let completed = PenghapusanBmnStatus::Completed;
        assert!(completed.allowed_transitions().is_empty());
    }

    #[test]
    fn test_penghapusan_status_labels() {
        assert_eq!(PenghapusanBmnStatus::Draft.label(), "Draft");
        assert_eq!(PenghapusanBmnStatus::SKSigned.label(), "SK Ditandatangani");
        assert_eq!(PenghapusanBmnStatus::Completed.label(), "Selesai");
    }
}
