[package]
name = "layanan-pidmil"
version.workspace = true
edition.workspace = true
authors = ["SIMPelv2 Team"]
description = "pidmil service for SIMPelv2"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["cors", "trace"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
deadpool-postgres = "0.14"
tokio-postgres = { version = "0.7", features = ["with-uuid-1", "with-chrono-0_4"] }
chrono = { workspace = true, features = ["serde"] }
garde = { version = "0.22", features = ["derive", "email"] }
thiserror = { workspace = true }
dotenvy = "0.15"

[features]
integration-tests = []
