/// Modul `admin`.
pub mod admin;
/// Modul `client_registration`.
pub mod client_policy;
/// Modul `satker`.
pub mod client_registration;
/// Modul `dcr_admin`.
pub mod dcr_admin;
/// Modul `spi_management`.
pub mod satker;
/// Modul `spi_management`.
pub mod spi_management;
