---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authenc
  labels:
    app.kubernetes.io/name: authenc
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secreton
  labels:
    app.kubernetes.io/name: secreton
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: layanan-integrasi
  labels:
    app.kubernetes.io/name: layanan-integrasi
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: layanan-perlengkapan
  labels:
    app.kubernetes.io/name: layanan-perlengkapan
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal
  labels:
    app.kubernetes.io/name: portal
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: perlengkapan
  labels:
    app.kubernetes.io/name: perlengkapan
automountServiceAccountToken: false
