[package]
name = "layanan-keuangan"
version.workspace = true
edition.workspace = true
authors = ["SIMPelv2 Team"]
description = "keuangan service for SIMPelv2"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["cors", "trace"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
deadpool-postgres = { workspace = true }
tokio-postgres = { workspace = true }
postgres-types = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
thiserror = { workspace = true }
garde = { workspace = true, features = ["derive"] }
jsonwebtoken = { workspace = true }
lib-common = { workspace = true, features = ["axum", "telemetry", "db"] }

[features]
integration-tests = []
