#!/usr/bin/env python3
"""Fail CI when a frontend route has no screenshot in the README gallery.

The gallery is the only place that claims "every page renders". Nothing in the
build reads it, so without this a route can land and the README keeps showing
the previous set — correct on the day it was generated, quietly incomplete
after the next router change.

Two sets are compared, and both are DERIVED:

  * expected — every navigable route in both frontends. Read from the same
    `screenshot-routes.py` the capture script consumes, so the gate and the
    sweep can never disagree about what "every route" means. That script walks
    the router nesting, which is what makes parameterised detail routes count;
    the curated `pub const` list in `routes.rs` omits them.
  * actual — the image references inside the README's autogenerated block.

Only the gallery is compared, not the image files: a stray PNG on disk is not
coverage, and requiring the README to name it is exactly the property worth
enforcing.

Stdlib only, and no browser or stack: this is a static parse, so it can run in
the same cheap invariants job as the other scope gates. Exit 0 when every route
appears, 1 otherwise.

Usage:  python3 infra/scripts/check-screenshot-coverage.py [--readme FILE]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROUTES_SCRIPT = REPO / "tests" / "e2e" / "screenshot-routes.py"

BEGIN = "<!-- BEGIN AUTOGENERATED SCREENSHOTS"
END = "<!-- END AUTOGENERATED SCREENSHOTS -->"

# Routes the sweep deliberately does not photograph, each with its reason. Kept
# here rather than in the capture script so the exclusion is visible to the
# reviewer of THIS file — an exclusion buried in the sweep looks like coverage.
ALLOWED_MISSING: dict[str, str] = {}


def expected_routes() -> list[str]:
    """Ask the sweep's own inventory script, so the two cannot drift apart.

    The inventory already emits absolute paths (they include each FE's base),
    so nothing is prefixed here — doing so produced
    `/portal/portal/admin` and reported all 65 routes as missing.
    """
    out = subprocess.run(
        [sys.executable, str(ROUTES_SCRIPT)],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    inv = json.loads(out)
    paths: list[str] = []
    for fe in inv.values():
        for r in fe["routes"]:
            paths.append(r if isinstance(r, str) else r["path"])
    return paths


def route_pattern(route: str) -> re.Pattern[str]:
    """Turn a declared route into a matcher for the captured URL.

    The inventory declares placeholders (`/bank-aset/daftar/:id`) while the
    sweep photographs the resolved URL (`/bank-aset/daftar/<uuid>`). Comparing
    the two as strings would report every detail page as uncovered, so each
    `:param` segment becomes a single-segment wildcard.
    """
    parts = []
    for seg in route.split("/"):
        if seg.startswith(":"):
            parts.append(r"[^/]+")
        else:
            parts.append(re.escape(seg))
    # Trailing slash is optional: the gallery caption and the router disagree
    # about it for index routes, and that is not a coverage difference.
    return re.compile("^" + "/".join(parts).rstrip("/") + "/?$")


def gallery_routes(readme: Path) -> set[str]:
    text = readme.read_text(encoding="utf-8")
    i, j = text.find(BEGIN), text.find(END)
    if i == -1 or j == -1:
        print(
            f"{readme} has no screenshot gallery block; expected markers "
            f"{BEGIN!r} … {END!r}",
            file=sys.stderr,
        )
        sys.exit(2)
    block = text[i:j]
    # Captions are the route, written as `**`<route>`**` — read the caption
    # rather than the filename so a renamed image does not read as a missing
    # route. The `(operator)` suffix marks a guard shot; strip it so it maps
    # back onto the route it guards.
    found: set[str] = set()
    for cap in re.findall(r"^\*\*`([^`]+)`", block, re.M):
        cap = re.sub(r"\s*\((?:operator|anon)\)\s*$", "", cap).strip()
        found.add(cap)
    return found


def missing_routes(readme: Path) -> list[str]:
    """Routes the inventory declares that the gallery does not show."""
    expected = expected_routes()
    actual = gallery_routes(readme)
    patterns = [(r, route_pattern(r)) for r in expected]
    covered = {r for r, p in patterns if any(p.match(a) for a in actual)}
    return [r for r, _ in patterns if r not in covered and r not in ALLOWED_MISSING]


def self_test() -> int:
    """Prove the gate is red for the regression it claims to catch.

    A gate that passes on a healthy repo proves nothing — the failure it exists
    for is a route that has no screenshot, and the only way to know it would
    notice is to delete one and watch it go red. (The neighbouring guards all
    learned this the same way: check-crate-ci-coverage's first version PASSED
    with the `run:` line deleted, because the step NAME still contained the
    command.)
    """
    failures: list[str] = []
    readme = (REPO / "README.md").read_text(encoding="utf-8")

    def run_on(text: str) -> list[str]:
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as fh:
            fh.write(text)
            tmp = Path(fh.name)
        try:
            return missing_routes(tmp)
        finally:
            tmp.unlink(missing_ok=True)

    # Case 1: healthy repo must be green.
    if run_on(readme):
        failures.append("repo sehat malah MERAH")

    # Case 2: drop exactly one caption+image and expect it to be reported.
    m = re.search(
        r"^\*\*`(/[^`]+)`\*\*\n\n!\[[^\]]*\]\([^)]+\)\n\n<sub>[^<]*</sub>\n\n",
        readme,
        re.M,
    )
    if not m:
        failures.append("tak menemukan satu entri galeri untuk dimutasi")
    else:
        dropped = m.group(1)
        got = run_on(readme[: m.start()] + readme[m.end() :])
        if dropped not in got:
            failures.append(f"rute dihapus ({dropped}) tak dilaporkan (dapat {got})")

    for f in failures:
        print(f"  GAGAL  {f}", file=sys.stderr)
    if failures:
        print(f"\nself-test GAGAL ({len(failures)} kasus)", file=sys.stderr)
        return 1
    print("self-test lulus (2 kasus)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--readme", default=str(REPO / "README.md"))
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="mutate a copy of the README and assert the gate goes red",
    )
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    missing = missing_routes(Path(args.readme))
    if missing:
        print(
            f"REFUSED: {len(missing)} route(s) have no screenshot in "
            f"{args.readme}:",
            file=sys.stderr,
        )
        for r in sorted(missing):
            print(f"  {r}", file=sys.stderr)
        print(
            "\nRun the sweep, then regenerate the gallery:\n"
            "  node tests/e2e/screenshots/capture.mjs\n"
            "  python3 tests/e2e/screenshots/check.py\n"
            "  python3 tests/e2e/screenshots/gallery.py "
            "--prefix docs/assets/screenshots/ --embed README.md",
            file=sys.stderr,
        )
        return 1

    print(
        f"ok: all {len(expected_routes())} route(s) are shown in the gallery"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
