apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: postgres-mtls
  namespace: simpelv2
spec:
  host: postgres-service.simpelv2.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
