apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-authenc-grpc
  namespace: simpelv2
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: authenc
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              component: backend
      ports:
        - protocol: TCP
          port: 9088
        - protocol: TCP
          port: 8088
