apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: authenc-permissive
  namespace: simpelv2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authenc
  mtls:
    mode: STRICT
