// ============================================================================
// Penghapusan BMN Models
// Description: Data models for Usulan SK Penghapusan BMN workflow
// Requirements: REQ-W001
//
// Flow:
//   Draft(4000) → SubmitWilayah(4001) → SubmitPusat(4003) → VerifikasiPusat(4004) →
//   KonsepSKGenerated(4005) → SKSigned(4006) → Completed(4007)
//   Validator Wilayah can return: ReturnedToOperator(4002)
//   Validator Pusat can reject: Rejected(4008)
// ============================================================================

use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;
use validator::Validate;

/// Workflow status codes for Usulan SK Penghapusan BMN
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(i32)]
#[derive(Default)]
pub enum PenghapusanBmnStatus {
    /// Draft by operator satker
    #[default]
    Draft = 4000,
    /// Submitted to Validator Wilayah
    SubmitWilayah = 4001,
    /// Returned to Operator by Validator Wilayah
    ReturnedToOperator = 4002,
    /// Forwarded to Validator Pusat by Validator Wilayah (kewenangan=PUSAT)
    SubmitPusat = 4003,
    /// Validator Pusat verifying
    VerifikasiPusat = 4004,
    /// Konsep SK generated by Validator Pusat
    KonsepSKGenerated = 4005,
    /// SK signed by Pusat (Jaksa Agung Muda Pembinaan) and PDF uploaded
    SKSigned = 4006,
    /// Process completed
    Completed = 4007,
    /// Rejected by Validator Pusat
    Rejected = 4008,
    /// V029 (Fase 1.9): Konsep SK generated by Validator Wilayah utk
    /// kewenangan=WILAYAH (mewakili Kepala Kejaksaan Tinggi).
    KonsepSKWilayahGenerated = 4010,
    /// V029 (Fase 1.9): SK signed by Kepala Kejati dan PDF uploaded.
    SKSignedWilayah = 4011,
}

impl PenghapusanBmnStatus {
    pub fn from_code(code: i32) -> Option<Self> {
        match code {
            4000 => Some(Self::Draft),
            4001 => Some(Self::SubmitWilayah),
            4002 => Some(Self::ReturnedToOperator),
            4003 => Some(Self::SubmitPusat),
            4004 => Some(Self::VerifikasiPusat),
            4005 => Some(Self::KonsepSKGenerated),
            4006 => Some(Self::SKSigned),
            4007 => Some(Self::Completed),
            4008 => Some(Self::Rejected),
            4010 => Some(Self::KonsepSKWilayahGenerated),
            4011 => Some(Self::SKSignedWilayah),
            _ => None,
        }
    }

    pub fn to_code(self) -> i32 {
        self as i32
    }

    pub fn label(&self) -> &'static str {
        match self {
            Self::Draft => "Draft",
            Self::SubmitWilayah => "Diajukan ke Validator Wilayah",
            Self::ReturnedToOperator => "Dikembalikan ke Operator",
            Self::SubmitPusat => "Diajukan ke Validator Pusat",
            Self::VerifikasiPusat => "Verifikasi Pusat",
            Self::KonsepSKGenerated => "Konsep SK Digenerate (Pusat)",
            Self::SKSigned => "SK Ditandatangani (Pusat)",
            Self::Completed => "Selesai",
            Self::Rejected => "Ditolak",
            Self::KonsepSKWilayahGenerated => "Konsep SK Digenerate (Wilayah)",
            Self::SKSignedWilayah => "SK Ditandatangani (Wilayah)",
        }
    }

    pub fn to_state_name(&self) -> &'static str {
        match self {
            Self::Draft => "DRAFT",
            Self::SubmitWilayah => "SUBMIT_WILAYAH",
            Self::ReturnedToOperator => "RETURNED_TO_OPERATOR",
            Self::SubmitPusat => "SUBMIT_PUSAT",
            Self::VerifikasiPusat => "VERIFIKASI_PUSAT",
            Self::KonsepSKGenerated => "KONSEP_SK_GENERATED",
            Self::SKSigned => "SK_SIGNED",
            Self::Completed => "COMPLETED",
            Self::Rejected => "REJECTED",
            Self::KonsepSKWilayahGenerated => "KONSEP_SK_WILAYAH_GENERATED",
            Self::SKSignedWilayah => "SK_SIGNED_WILAYAH",
        }
    }

    pub fn from_state_name(name: &str) -> Option<Self> {
        match name {
            "DRAFT" => Some(Self::Draft),
            "SUBMIT_WILAYAH" | "SUBMITTED" => Some(Self::SubmitWilayah),
            "RETURNED_TO_OPERATOR" => Some(Self::ReturnedToOperator),
            "SUBMIT_PUSAT" | "REVIEWED" => Some(Self::SubmitPusat),
            "VERIFIKASI_PUSAT" => Some(Self::VerifikasiPusat),
            "KONSEP_SK_GENERATED" => Some(Self::KonsepSKGenerated),
            "SK_SIGNED" | "APPROVED" => Some(Self::SKSigned),
            "COMPLETED" => Some(Self::Completed),
            "REJECTED" => Some(Self::Rejected),
            "KONSEP_SK_WILAYAH_GENERATED" => Some(Self::KonsepSKWilayahGenerated),
            "SK_SIGNED_WILAYAH" => Some(Self::SKSignedWilayah),
            _ => None,
        }
    }

    /// Check if transition to target status is allowed
    ///
    /// Branching SubmitWilayah → KonsepSKWilayahGenerated atau SubmitPusat
    /// hanya satu yg valid per entity berdasarkan `kewenangan_penetap_sk`,
    /// tapi state machine alone tidak punya akses ke entity field — service
    /// layer mem-validate kewenangan match dgn transition target.
    pub fn can_transition_to(&self, target: Self) -> bool {
        use PenghapusanBmnStatus::*;
        match self {
            Draft => matches!(target, SubmitWilayah),
            // V029 (Fase 1.9): jalur kewenangan WILAYAH skip Pusat —
            // langsung KonsepSKWilayahGenerated.
            SubmitWilayah => matches!(
                target,
                SubmitPusat | ReturnedToOperator | KonsepSKWilayahGenerated
            ),
            ReturnedToOperator => matches!(target, SubmitWilayah),
            SubmitPusat => matches!(target, VerifikasiPusat),
            VerifikasiPusat => matches!(target, KonsepSKGenerated | Rejected),
            KonsepSKGenerated => matches!(target, SKSigned),
            SKSigned => matches!(target, Completed),
            // V029: jalur WILAYAH.
            KonsepSKWilayahGenerated => matches!(target, SKSignedWilayah),
            SKSignedWilayah => matches!(target, Completed),
            Completed | Rejected => false,
        }
    }

    pub fn allowed_transitions(&self) -> Vec<Self> {
        use PenghapusanBmnStatus::*;
        match self {
            Draft => vec![SubmitWilayah],
            SubmitWilayah => vec![SubmitPusat, ReturnedToOperator, KonsepSKWilayahGenerated],
            ReturnedToOperator => vec![SubmitWilayah],
            SubmitPusat => vec![VerifikasiPusat],
            VerifikasiPusat => vec![KonsepSKGenerated, Rejected],
            KonsepSKGenerated => vec![SKSigned],
            SKSigned => vec![Completed],
            KonsepSKWilayahGenerated => vec![SKSignedWilayah],
            SKSignedWilayah => vec![Completed],
            Completed | Rejected => vec![],
        }
    }

    /// Normalize a `status` filter string from the API into the canonical
    /// state names stored in the DB (`to_state_name()`).
    ///
    /// Accepts a comma-separated list and legacy/UI aliases (handled by
    /// [`from_state_name`], e.g. `SUBMITTED`→`SUBMIT_WILAYAH`,
    /// `REVIEWED`→`SUBMIT_PUSAT`, `APPROVED`→`SK_SIGNED`). Whitespace is
    /// trimmed, matching is case-insensitive, and unknown tokens are dropped
    /// so a bad value can never silently match every row.
    ///
    /// [`from_state_name`]: PenghapusanBmnStatus::from_state_name
    pub fn normalize_status_filter(raw: &str) -> Vec<String> {
        raw.split(',')
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .filter_map(|s| {
                Self::from_state_name(&s.to_uppercase()).map(|st| st.to_state_name().to_string())
            })
            .collect()
    }
}

/// Penghapusan BMN entity
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenghapusanBmn {
    pub id: Uuid,
    pub satker_id: Uuid,
    pub asset_id: Uuid,
    pub kode_barang: String,
    pub nama_barang: String,
    pub nup: String,
    pub tanggal_penghapusan: NaiveDate,
    pub alasan: String,
    pub metode_penghapusan: String,
    /// Nilai perolehan aset (harga pembelian). Menggantikan `nilai_residu`
    /// yg dipakai di skema lama; sengaja berbeda nama agar konsumen API
    /// memperbarui pemakaian (lihat V029).
    pub nilai_perolehan: Option<f64>,
    /// TRUE jika `nilai_perolehan` di-backfill otomatis dari kolom legacy
    /// `nilai_residu`. UI dapat menampilkan banner "perlu diverifikasi".
    pub nilai_perolehan_dari_backfill: bool,
    pub status: String,
    pub status_kode: i32,

    // Lampiran
    pub lampiran_persyaratan: Option<String>,
    pub lampiran_pendukung: Value,
    pub catatan_operator: Option<String>,

    // Validator Wilayah
    pub catatan_validator_wilayah: Option<String>,
    pub validator_wilayah_id: Option<Uuid>,
    pub tanggal_submit_wilayah: Option<DateTime<Utc>>,
    pub tanggal_verifikasi_wilayah: Option<DateTime<Utc>>,

    // Validator Pusat
    pub catatan_validator_pusat: Option<String>,
    pub validator_pusat_id: Option<Uuid>,
    pub tanggal_submit_pusat: Option<DateTime<Utc>>,
    pub tanggal_verifikasi_pusat: Option<DateTime<Utc>>,

    // SK Document — jalur PUSAT (kewenangan_penetap_sk = 'PUSAT')
    pub konsep_sk_url: Option<String>,
    pub konsep_sk_generated_at: Option<DateTime<Utc>>,
    pub signed_sk_pdf_url: Option<String>,
    pub signed_sk_pdf_uploaded_at: Option<DateTime<Utc>>,
    pub is_completed: bool,

    // Surat Usulan file upload (V030, Fase 0.6)
    pub surat_usulan_file_url: Option<String>,
    pub surat_usulan_uploaded_at: Option<DateTime<Utc>>,

    // V029 (Fase 1.9): Dual kewenangan SK
    /// Kewenangan penetap SK: 'PUSAT' (Jaksa Agung Muda Pembinaan) atau
    /// 'WILAYAH' (Kepala Kejaksaan Tinggi). Default 'PUSAT' utk backward
    /// compat dgn data lama.
    pub kewenangan_penetap_sk: String,
    /// Label jabatan penetap (cth: "Jaksa Agung Muda Pembinaan" atau
    /// "Kepala Kejaksaan Tinggi DKI Jakarta"). Disimpan utk audit.
    pub penetap_sk_jabatan: Option<String>,
    // SK Document — jalur WILAYAH (kewenangan_penetap_sk = 'WILAYAH')
    pub konsep_sk_wilayah_url: Option<String>,
    pub konsep_sk_wilayah_pdf_url: Option<String>,
    pub konsep_sk_wilayah_generated_at: Option<DateTime<Utc>>,
    pub signed_sk_wilayah_pdf_url: Option<String>,
    pub signed_sk_wilayah_pdf_uploaded_at: Option<DateTime<Utc>>,

    // Legacy fields
    pub document_id: Option<Uuid>,
    pub document_url: Option<String>,

    pub created_by: Uuid,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Create penghapusan BMN request
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreatePenghapusanBmnRequest {
    pub satker_id: Uuid,
    pub asset_id: Uuid,
    pub kode_barang: String,
    #[validate(length(min = 1, max = 255))]
    pub nama_barang: String,
    #[validate(length(min = 1, max = 50))]
    pub nup: String,
    pub tanggal_penghapusan: NaiveDate,
    #[validate(length(min = 10, max = 1000))]
    pub alasan: String,
    #[validate(length(min = 1, max = 100))]
    pub metode_penghapusan: String,
    pub nilai_perolehan: Option<f64>,
    // Lampiran persyaratan (required)
    #[validate(length(min = 1, message = "Lampiran persyaratan wajib dilampirkan"))]
    pub lampiran_persyaratan: String,
    pub catatan_operator: Option<String>,
    /// V029 (Fase 1.9): Kewenangan penetap SK — 'PUSAT' atau 'WILAYAH'.
    /// Default 'PUSAT' (backward compat). Setelah dipilih, workflow
    /// branching ditentukan di service: WILAYAH = SubmitWilayah →
    /// KonsepSKWilayahGenerated (skip Pusat); PUSAT = jalur normal.
    #[serde(default = "default_kewenangan")]
    pub kewenangan_penetap_sk: String,
    /// Label jabatan penetap (cth: "Kepala Kejaksaan Tinggi DKI Jakarta").
    /// Optional; jika None server isi default berdasarkan kewenangan.
    pub penetap_sk_jabatan: Option<String>,
    /// V036 (Fase 2.8): daftar item BMN multi-item. Bila kosong/None, service
    /// fallback ke item tunggal dari kolom kode_barang/nama_barang/nup di atas
    /// (backward compat). Item pertama menjadi "item utama" tabel induk.
    #[serde(default)]
    pub items: Vec<CreatePenghapusanBmnItemRequest>,
}

/// Satu item BMN dalam usulan multi-item (Fase 2.8).
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreatePenghapusanBmnItemRequest {
    pub asset_id: Option<Uuid>,
    #[validate(length(min = 1, max = 50))]
    pub kode_barang: String,
    #[validate(length(min = 1, max = 255))]
    pub nama_barang: String,
    #[validate(length(min = 1, max = 50))]
    pub nup: String,
    pub nilai_perolehan: Option<f64>,
    pub kondisi: Option<String>,
}

/// Satu item BMN tersimpan (row `perlengkapan.penghapusan_bmn_item`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenghapusanBmnItem {
    pub id: Uuid,
    pub penghapusan_id: Uuid,
    pub asset_id: Option<Uuid>,
    pub kode_barang: String,
    pub nama_barang: String,
    pub nup: String,
    pub nilai_perolehan: Option<f64>,
    pub nilai_perolehan_dari_backfill: bool,
    pub kondisi: Option<String>,
    pub urutan: i32,
}

impl PenghapusanBmnItem {
    pub fn from_row(row: &tokio_postgres::Row) -> Self {
        Self {
            id: row.get("id"),
            penghapusan_id: row.get("penghapusan_id"),
            asset_id: row.try_get("asset_id").ok().flatten(),
            kode_barang: row.get("kode_barang"),
            nama_barang: row.get("nama_barang"),
            nup: row.get("nup"),
            nilai_perolehan: row.try_get("nilai_perolehan").ok().flatten(),
            nilai_perolehan_dari_backfill: row
                .try_get("nilai_perolehan_dari_backfill")
                .unwrap_or(false),
            kondisi: row.try_get("kondisi").ok().flatten(),
            urutan: row.try_get("urutan").unwrap_or(1),
        }
    }
}

fn default_kewenangan() -> String {
    "PUSAT".to_string()
}

/// Update penghapusan BMN request
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct UpdatePenghapusanBmnRequest {
    pub tanggal_penghapusan: Option<NaiveDate>,
    #[validate(length(min = 10, max = 1000))]
    pub alasan: Option<String>,
    #[validate(length(min = 1, max = 100))]
    pub metode_penghapusan: Option<String>,
    pub nilai_perolehan: Option<f64>,
    pub lampiran_persyaratan: Option<String>,
    pub catatan_operator: Option<String>,
}

/// Penghapusan BMN list filters
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenghapusanBmnFilters {
    pub satker_id: Option<Uuid>,
    pub status: Option<String>,
    pub status_kode: Option<i32>,
    pub metode_penghapusan: Option<String>,
    pub tahun: Option<i32>,
}

/// Request for validator wilayah action
#[derive(Debug, Clone, Deserialize)]
pub struct ValidatorWilayahActionRequest {
    /// "forward" to forward to pusat, "return" to return to operator
    pub aksi: String,
    pub catatan: Option<String>,
}

/// Request for validator pusat action
#[derive(Debug, Clone, Deserialize)]
pub struct ValidatorPusatActionRequest {
    /// "verify" to proceed, "reject" to reject
    pub aksi: String,
    pub catatan: Option<String>,
}

/// Request to upload signed SK PDF
#[derive(Debug, Clone, Deserialize)]
pub struct UploadSignedSKRequest {
    pub signed_sk_pdf_url: String,
}

/// Request for workflow transition
#[derive(Debug, Clone, Deserialize)]
pub struct WorkflowTransitionRequest {
    pub target_status: i32,
    pub catatan: Option<String>,
}

/// Penghapusan BMN detail response
#[derive(Debug, Clone, Serialize)]
pub struct PenghapusanBmnDetailResponse {
    #[serde(flatten)]
    pub penghapusan: PenghapusanBmn,
    pub allowed_transitions: Vec<PenghapusanTransitionInfo>,
    pub can_generate_sk: bool,
    pub can_upload_signed_sk: bool,
    /// V036 (Fase 2.8): daftar item BMN dalam usulan ini (≥1, terurut).
    #[serde(default)]
    pub items: Vec<PenghapusanBmnItem>,
}

/// Transition info
#[derive(Debug, Clone, Serialize)]
pub struct PenghapusanTransitionInfo {
    pub status_kode: i32,
    pub status_nama: String,
    pub requires_comment: bool,
}

/// Hasil verifikasi aset ke SIMAN (Fase 2.3). Dipakai validator saat tahap
/// VerifikasiPusat untuk memastikan aset yg diusulkan hapus masih terdaftar
/// di SIMAN dan kondisinya konsisten sebelum SK digenerate. Mencegah
/// penghapusan aset yg sudah tidak ada / data tidak cocok.
#[derive(Debug, Clone, Serialize)]
pub struct SimanAssetVerification {
    /// NUP yg diverifikasi (dari usulan).
    pub nup: String,
    /// `true` jika NUP ditemukan di SIMAN (`integrasi.siman_aset`).
    pub ditemukan: bool,
    /// kode_barang pada usulan.
    pub kode_barang_diajukan: String,
    /// kode_barang menurut SIMAN (jika ditemukan).
    pub kode_barang_siman: Option<String>,
    /// `true` jika kode_barang usulan == kode_barang SIMAN.
    pub kode_barang_cocok: bool,
    /// Nama barang menurut SIMAN.
    pub nama_barang_siman: Option<String>,
    pub merk: Option<String>,
    /// Kondisi aset menurut SIMAN (BAIK / RR / RB).
    pub kondisi: Option<String>,
    /// Nilai perolehan menurut SIMAN.
    pub nilai_perolehan_siman: Option<f64>,
    /// Verdict singkat untuk ditampilkan ke validator.
    pub pesan: String,
    /// `true` bila aman dilanjutkan (ditemukan + kode_barang cocok).
    pub layak_lanjut: bool,
}

impl PenghapusanBmn {
    /// Create from database row
    pub fn from_row(row: &tokio_postgres::Row) -> Self {
        let status_str: String = row.get("status");
        let status_kode = PenghapusanBmnStatus::from_state_name(&status_str)
            .map(|s| s.to_code())
            .unwrap_or(4000);
        Self {
            id: row.get("id"),
            satker_id: row.get("satker_id"),
            asset_id: row.get("asset_id"),
            kode_barang: row.get("kode_barang"),
            nama_barang: row.get("nama_barang"),
            nup: row.get("nup"),
            tanggal_penghapusan: row.get("tanggal_penghapusan"),
            alasan: row.get("alasan"),
            metode_penghapusan: row.get("metode_penghapusan"),
            nilai_perolehan: row.try_get("nilai_perolehan").ok().flatten(),
            nilai_perolehan_dari_backfill: row
                .try_get("nilai_perolehan_dari_backfill")
                .unwrap_or(false),
            status: status_str,
            status_kode,
            lampiran_persyaratan: row.try_get("lampiran_persyaratan").ok().flatten(),
            lampiran_pendukung: row
                .try_get("lampiran_pendukung")
                .unwrap_or(serde_json::json!([])),
            catatan_operator: row.try_get("catatan_operator").ok().flatten(),
            catatan_validator_wilayah: row.try_get("catatan_validator_wilayah").ok().flatten(),
            validator_wilayah_id: row.try_get("validator_wilayah_id").ok().flatten(),
            tanggal_submit_wilayah: row.try_get("tanggal_submit_wilayah").ok().flatten(),
            tanggal_verifikasi_wilayah: row.try_get("tanggal_verifikasi_wilayah").ok().flatten(),
            catatan_validator_pusat: row.try_get("catatan_validator_pusat").ok().flatten(),
            validator_pusat_id: row.try_get("validator_pusat_id").ok().flatten(),
            tanggal_submit_pusat: row.try_get("tanggal_submit_pusat").ok().flatten(),
            tanggal_verifikasi_pusat: row.try_get("tanggal_verifikasi_pusat").ok().flatten(),
            konsep_sk_url: row.try_get("konsep_sk_url").ok().flatten(),
            konsep_sk_generated_at: row.try_get("konsep_sk_generated_at").ok().flatten(),
            signed_sk_pdf_url: row.try_get("signed_sk_pdf_url").ok().flatten(),
            signed_sk_pdf_uploaded_at: row.try_get("signed_sk_pdf_uploaded_at").ok().flatten(),
            is_completed: row.try_get("is_completed").unwrap_or(false),
            surat_usulan_file_url: row.try_get("surat_usulan_file_url").ok().flatten(),
            surat_usulan_uploaded_at: row.try_get("surat_usulan_uploaded_at").ok().flatten(),
            // V029 (Fase 1.9): Dual kewenangan SK
            kewenangan_penetap_sk: row
                .try_get::<_, String>("kewenangan_penetap_sk")
                .unwrap_or_else(|_| "PUSAT".to_string()),
            penetap_sk_jabatan: row.try_get("penetap_sk_jabatan").ok().flatten(),
            konsep_sk_wilayah_url: row.try_get("konsep_sk_wilayah_url").ok().flatten(),
            konsep_sk_wilayah_pdf_url: row.try_get("konsep_sk_wilayah_pdf_url").ok().flatten(),
            konsep_sk_wilayah_generated_at: row
                .try_get("konsep_sk_wilayah_generated_at")
                .ok()
                .flatten(),
            signed_sk_wilayah_pdf_url: row.try_get("signed_sk_wilayah_pdf_url").ok().flatten(),
            signed_sk_wilayah_pdf_uploaded_at: row
                .try_get("signed_sk_wilayah_pdf_uploaded_at")
                .ok()
                .flatten(),
            document_id: row.get("document_id"),
            document_url: row.get("document_url"),
            created_by: row.get("created_by"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        }
    }
}

/// Lampiran pendukung Usulan SK Penghapusan BMN (V030).
///
/// Multi-file opsional; file disimpan via `DocumentStorage`, baris ini
/// hanya metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenghapusanBmnLampiran {
    pub id: Uuid,
    pub penghapusan_id: Uuid,
    pub nama: String,
    pub file_url: String,
    pub content_type: Option<String>,
    pub size_bytes: Option<i64>,
    pub uploaded_by: Option<Uuid>,
    pub uploaded_at: DateTime<Utc>,
}

impl PenghapusanBmnLampiran {
    pub fn from_row(row: &tokio_postgres::Row) -> Self {
        Self {
            id: row.get("id"),
            penghapusan_id: row.get("penghapusan_id"),
            nama: row.get("nama"),
            file_url: row.get("file_url"),
            content_type: row.try_get("content_type").ok().flatten(),
            size_bytes: row.try_get("size_bytes").ok().flatten(),
            uploaded_by: row.try_get("uploaded_by").ok().flatten(),
            uploaded_at: row.get("uploaded_at"),
        }
    }
}

/// Response untuk endpoint upload lampiran multipart.
#[derive(Debug, Clone, Serialize)]
pub struct UploadLampiranResponse {
    /// URL Surat Usulan (jika field `surat_usulan` ikut di-upload pada
    /// request ini). `None` jika tidak ada — caller dpt menggabungkan
    /// dgn nilai yg sudah ada di entity.
    pub surat_usulan_file_url: Option<String>,
    /// Lampiran pendukung yg baru di-upload pada request ini.
    pub lampiran: Vec<PenghapusanBmnLampiran>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_penghapusan_status_flow() {
        let draft = PenghapusanBmnStatus::Draft;
        assert!(draft.can_transition_to(PenghapusanBmnStatus::SubmitWilayah));
        assert!(!draft.can_transition_to(PenghapusanBmnStatus::SubmitPusat));

        let wil = PenghapusanBmnStatus::SubmitWilayah;
        assert!(wil.can_transition_to(PenghapusanBmnStatus::SubmitPusat));
        assert!(wil.can_transition_to(PenghapusanBmnStatus::ReturnedToOperator));

        let verif = PenghapusanBmnStatus::VerifikasiPusat;
        assert!(verif.can_transition_to(PenghapusanBmnStatus::KonsepSKGenerated));
        assert!(verif.can_transition_to(PenghapusanBmnStatus::Rejected));
        assert!(!verif.can_transition_to(PenghapusanBmnStatus::ReturnedToOperator));

        let signed = PenghapusanBmnStatus::SKSigned;
        assert!(signed.can_transition_to(PenghapusanBmnStatus::Completed));

        let completed = PenghapusanBmnStatus::Completed;
        assert!(completed.allowed_transitions().is_empty());
    }

    #[test]
    fn test_normalize_status_filter() {
        // Legacy/UI aliases map to the canonical names stored in the DB.
        assert_eq!(
            PenghapusanBmnStatus::normalize_status_filter("SUBMITTED"),
            vec!["SUBMIT_WILAYAH"]
        );
        assert_eq!(
            PenghapusanBmnStatus::normalize_status_filter("REVIEWED"),
            vec!["SUBMIT_PUSAT"]
        );
        // Comma-separated list, whitespace, and case are all handled; the
        // canonical name passes through unchanged.
        assert_eq!(
            PenghapusanBmnStatus::normalize_status_filter("konsep_sk_generated, COMPLETED"),
            vec!["KONSEP_SK_GENERATED", "COMPLETED"]
        );
        // Unknown tokens are dropped (never silently match every row); the
        // valid sibling still comes through.
        assert_eq!(
            PenghapusanBmnStatus::normalize_status_filter("DOCUMENT_GENERATED,COMPLETED"),
            vec!["COMPLETED"]
        );
        // All-unknown / empty → empty list → caller skips the filter entirely.
        assert!(PenghapusanBmnStatus::normalize_status_filter("BOGUS").is_empty());
        assert!(PenghapusanBmnStatus::normalize_status_filter("  ,  ").is_empty());
    }

    #[test]
    fn test_penghapusan_status_labels() {
        assert_eq!(PenghapusanBmnStatus::Draft.label(), "Draft");
        // V029 (Fase 1.9): label spesifik per jalur kewenangan.
        assert_eq!(
            PenghapusanBmnStatus::SKSigned.label(),
            "SK Ditandatangani (Pusat)"
        );
        assert_eq!(
            PenghapusanBmnStatus::SKSignedWilayah.label(),
            "SK Ditandatangani (Wilayah)"
        );
        assert_eq!(PenghapusanBmnStatus::Completed.label(), "Selesai");
    }

    #[test]
    fn test_penghapusan_wilayah_path_transitions() {
        use PenghapusanBmnStatus::*;
        // SubmitWilayah → KonsepSKWilayahGenerated (new path)
        assert!(SubmitWilayah.can_transition_to(KonsepSKWilayahGenerated));
        // KonsepSKWilayahGenerated → SKSignedWilayah
        assert!(KonsepSKWilayahGenerated.can_transition_to(SKSignedWilayah));
        // SKSignedWilayah → Completed
        assert!(SKSignedWilayah.can_transition_to(Completed));
        // Not allowed: skip steps
        assert!(!SubmitWilayah.can_transition_to(SKSignedWilayah));
        assert!(!KonsepSKWilayahGenerated.can_transition_to(SKSigned));
    }

    #[test]
    fn test_status_code_wilayah_roundtrip() {
        // V029: kode 4010/4011 baru harus roundtrip.
        assert_eq!(
            PenghapusanBmnStatus::from_code(4010),
            Some(PenghapusanBmnStatus::KonsepSKWilayahGenerated)
        );
        assert_eq!(
            PenghapusanBmnStatus::from_code(4011),
            Some(PenghapusanBmnStatus::SKSignedWilayah)
        );
        assert_eq!(
            PenghapusanBmnStatus::KonsepSKWilayahGenerated.to_code(),
            4010
        );
        assert_eq!(PenghapusanBmnStatus::SKSignedWilayah.to_code(), 4011);
    }
}
