"apiVersion": v1
"kind": Service
"metadata":
  "name": badiklat
  "namespace": simpelv2
"spec":
  "selector":
    "app": badiklat
  "ports":
  - "name": port-0
    "port": 3000
    "targetPort": 3000
