"apiVersion": apps/v1
"kind": Deployment
"metadata":
  "name": nginx
  "namespace": simpelv2
"spec":
  "replicas": 1
  "selector":
    "matchLabels":
      "app": nginx
  "template":
    "metadata":
      "labels":
        "app": nginx
    "spec":
      "restartPolicy": Always
      "containers":
      - "name": nginx
        "image": nginx:stable-alpine
        "imagePullPolicy": IfNotPresent
        "ports":
        - "containerPort": 80
        "volumeMounts": []
      "volumes": []
