apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - simpelv2-config.yaml
  - backend-config.yaml
  - postgres-init-config.yaml

generatorOptions:
  disableNameSuffixHash: true
