[build]
target = "index.html"
dist = "dist"
release = true
wasm_opt = false

[serve]
port = 8083
addresses = ["0.0.0.0"]
open = false

[watch]
watch = ["src", "styles"]
ignore = ["target", "dist", "Cargo.lock", ".git"]
debounce = 100
