"apiVersion": kustomize.config.k8s.io/v1beta1
"kind": Kustomization
"namespace": simpelv2
"resources":
- namespace.yaml
- db-pvc.yaml
- monitoring-1.yaml
- monitoring-2.yaml
- ingress.yaml
- badiklat-deployment.yaml
- badiklat-service.yaml
- datun-deployment.yaml
- datun-service.yaml
- intel-deployment.yaml
- intel-service.yaml
- pembinaan-deployment.yaml
- pembinaan-service.yaml
- pemulihan-aset-deployment.yaml
- pemulihan-aset-service.yaml
- pengawasan-deployment.yaml
- pengawasan-service.yaml
- pidmil-deployment.yaml
- pidmil-service.yaml
- pidsus-deployment.yaml
- pidsus-service.yaml
- pidum-deployment.yaml
- pidum-service.yaml
- portal-deployment.yaml
- portal-service.yaml
- gerbang-deployment.yaml
- gerbang-service.yaml
- src-deployment.yaml
- src-service.yaml
- db-deployment.yaml
- db-service.yaml
- nginx-deployment.yaml
- nginx-service.yaml
- db-simpelv2-deployment.yaml
- db-simpelv2-service.yaml
- db-simpelv2-secret.yaml
