/// Modul `broker`.
pub mod broker;
/// Modul `federated_auth`.
pub mod federated_auth;
/// Modul `federated_login`.
pub mod federated_login;
/// Modul `federation_admin`.
pub mod federation_admin;
/// Modul `jit_admin_service`.
pub mod jit_admin_service;
/// Modul `social`.
pub mod saml;
/// Modul `social`.
pub mod social;
/// Modul `sso`.
/// Modul `spi_federation`.
pub mod spi_federation;
/// Modul `sso`.
pub mod sso;
