{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
  labels:
    {{- include "simpel.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value }}
globalDefault: false
preemptionPolicy: {{ .Values.priorityClass.preemptionPolicy }}
description: {{ .Values.priorityClass.description | quote }}
{{- end }}
