apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authenc.fullname" . }}-db
  labels:
    {{- include "authenc.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  {{- with .Values.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
