"apiVersion": v1
"kind": ConfigMap
"metadata":
  "name": grafana-datasource
  "namespace": simpelv2
"data":
  "datasource.yml": "\napiVersion: 1\ndatasources:\n  - name: Prometheus\n    type: prometheus\n    access: proxy\n    url:\
    \ http://prometheus:9090\n    isDefault: true\n"
