"apiVersion": kustomize.config.k8s.io/v1beta1
"kind": Kustomization
"namespace": simpelv2
"resources":
- namespace.yaml
- db-simpelv2-pvc.yaml
- ingress.yaml
- prometheus.yaml
- grafana.yaml
- db-simpelv2-deployment.yaml
- db-simpelv2-service.yaml
- nginx-deployment.yaml
- nginx-service.yaml
- gerbang-deployment.yaml
- gerbang-service.yaml
- antarmuka-deployment.yaml
- antarmuka-service.yaml
- layanan-keamanan-deployment.yaml
- layanan-keamanan-service.yaml
- layanan-audit-deployment.yaml
- layanan-audit-service.yaml
- layanan-integrasi-deployment.yaml
- layanan-integrasi-service.yaml
