[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/perlengkapan/"

[build.wasm-bindgen]
target = "web"
typescript = false
debug = false
demangle = false
keep-debug = false
no-modules-global = "wasm_bindgen"
reference-types = true
weak-refs = true

[build.rust]
optimization-level = "z"
debug = false
lto = true
codegen-units = 1

[serve]
port = 8093
addresses = ["0.0.0.0"]
open = false
no_autoreload = true
